name       : libdecor
version    : 0.1.0
release    : 1
source     :
    - https://gitlab.gnome.org/jadahl/libdecor/-/archive/0.1.0/libdecor-0.1.0.tar.gz : 1d5758cb49dcb9ceaa979ad14ceb6cdf39282af5ce12ebe6073dd193d6b2fb5e
license    : MIT
component  : desktop.library
emul32     : yes
summary    : Client-side decorations library for Wayland clients
description: |
    Client-side decorations library for Wayland clients
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(pangocairo)
    - pkgconfig32(wayland-egl)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure -Ddemo=false
build      : |
    %ninja_build
install    : |
    %ninja_install
